### ISSUE TITLE
Feature Request: Bot Command Scope

### ISSUE THREAD

**Issue by tsmith111992** [cotestatnt/AsyncTelegram2#104]
I was looking through the code and did not see a way to set the command scope. Was hoping that this might be a feature that could be incorporated.

Thanks

**Comment by henkjannl** [comment]
Hi,

I'm not sure if this is what you are looking for, but I was looking for how to set the default commands and found that this is working:

  myBot.setMyCommands("/start", "start new session");
  myBot.setMyCommands("/help",  "get help");

You can call the function multiple times to add additional commands. Hope this helps.

@cotestatnt may be good to add a line in the readme for this. I was trying to submit two JSON lists to the  function until I found out it is much simpler :-)
