### ISSUE TITLE
prevent restart loop

### ISSUE THREAD

**Issue by sanderkob** [cotestatnt/AsyncTelegram2#114]
I have implemented a restart command in my bot. When I issue the command `/restart`,  in my code this is interpreted and an `ESP.restart() `command is issued. <br>Apparently the message queue is not cleared because after restart the first message received is `/restart` and again an `ESP.restart()` command is issued.<br> This results in an endless loop. 
I can break the restart loop by sending the command `https://api.telegram.org/bot_token/getUpdates` in a web browser, noting the update_id, incrementing it by1, then send the command <br>`https://api.telegram.org/bot_token/getUpdates?offset=<update_id+1>`<br>How can I programmatically update the message queue before issuing the `ESP.restart()` command?<br> I tried <br>
```
getNewMessage(msg);
ESP.restart();
```
 but that does not work.

**Comment by cotestatnt** [comment]
Hi @sanderkob 
This is the same issue as https://github.com/cotestatnt/AsyncTelegram2/issues/102

**Comment by sanderkob** [comment]
Correct, my oversight.
