### ISSUE TITLE
languageCode

### ISSUE THREAD

**Issue by WonderCRM** [cotestatnt/AsyncTelegram2#12]
Please add the variable **languageCode** to **AsyncTelegram2.cpp** :: line 210+

`message.sender.languageCode  = updateDoc["result"][0]["message"]["from"]["language_code"];`

**Comment by cotestatnt** [comment]
Thanks @WonderCRM 
It was expected in the `struct TBUser`, but I had forgotten or perhaps accidentally removed the line of code.

**Comment by WonderCRM** [comment]
Thanks!
