### ISSUE TITLE
is there an END for bots?

### ISSUE THREAD

**Issue by MassiPi** [cotestatnt/AsyncTelegram2#14]
Hello,
is it possible to "end" a bot after beginning it?
i'd like to be able to enable/disable bot in runtime, is it possible?
thanks

**Comment by cotestatnt** [comment]
Not explicit, but you can simply stop calling the method `getNewMessages()`.
After a while the connection will be closed from server side, and when you need again will be reopened from bot.

**Comment by MassiPi** [comment]
ok so without calling the getNewMessage() the bot is not exchanging anything with the server, right? thank you!

**Comment by cotestatnt** [comment]
Exactly!
