### ISSUE TITLE
change parse_mode to "MarkdownV2" or "HTML"

### ISSUE THREAD

**Issue by DerDoubleD** [cotestatnt/AsyncTelegram2#16]
how can i change the parse_mode to "MarkdownV2" or "HTML"?

best regards
Daniel

**Comment by cotestatnt** [comment]
``..........
  ..........
  // local variable to store telegram message data
  TBMessage msg;

  // if there is an incoming message...
  if (myBot.getNewMessage(msg)) {    
    // Send a message to your public channel
    String message ;
    message += "<b>Bold Text</b>";
    msg.isHTMLenabled = true;
    // msg.isMarkdownEnabled = true;
    myBot.sendMessage(msg, message);
  }
  .........
  .........
```

**Comment by DerDoubleD** [comment]
> ```
> ........
>  
>   // local variable to store telegram message data
>   TBMessage msg;
> 
>   // if there is an incoming message...
>   if (myBot.getNewMessage(msg)) {    
>     // Send a message to your public channel
>     String message ;
>     message += "<b>Bold Text</b>";
>     msg.isHTMLenabled = true;
>     // msg.isMarkdownEnabled = true;
>     myBot.sendMessage(msg, message);
>   }
> .........
> ```

Thanks a lot, that is exactly what I have been looking for!
