### ISSUE TITLE
Bot Not receiving Channel Messages

### ISSUE THREAD

**Issue by DavidLightcraft** [cotestatnt/AsyncTelegram2#24]
Good day Tolentino,
I dont know if anyone had the same issue, I found no info, so I thought to ask you directly.

When I use 
myBotgetNewMessage(msg)

I do not receive messages on my ESP8266 from a groupchat where my bot is an admin. Also my bot's privacy was set as public, even if I start the message with "/xxxxx" or "@mybot" I do not receive any message typed in a group.

I do receive the messages on the esp8266 from direct message to my bot.
I would like to be able to use a group, for transparency and to have all messages in one place, as a security and automation of my home where me and my family can message the bot to open door or gates or get alarms.

Thank you.

**Comment by cotestatnt** [comment]
Hi @DavidLightcraft 
Sorry for very late reply, but i was very plenty of work this last months.

Actually the bot can only send messages to channel and not read back them. 
Honestly, I haven't investigated whether this is really possible, but you can certainly achieve this with groups. You need only to find the group ID wich is a negative integer

Once you have created your own group, you can add the bot **@getidsbot** thath will reply to you with a dump of groups properties included the ID. At this point you can remove and add your bot and all other usersyou need.

Example:
```
    myBot.sendTo(-532497195, "Hello to group from myBot");
```
