### ISSUE TITLE
__FILENAME__ already defined warning using ESP32 SDK

### ISSUE THREAD

**Issue by DeWonderMan** [cotestatnt/AsyncTelegram2#26]
Thanks for the great library. 

Using the ESP32 SDK, installed using [Espressif installation guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) results in a __FILENAME__ already defined warning:

```
.../Documents/Arduino/libraries/AsyncTelegram2/src/serial_log.h:10: warning: "__FILENAME__" redefined
 #define __FILENAME__ (strrchr(__FILE__, '\\') ? strrchr(__FILE__, '\\') + 1 : __FILE__)
```

The warning indicates it is already defined in the ESP32 SDK at:
```
...Arduino15/packages/esp32/hardware/esp32/2.0.1/tools/sdk/esp32/include/newlib/platform_include/assert.h:38: note: this is the location of the previous definition
 #define __FILENAME__ (__builtin_strrchr( "/" __FILE__, '/') + 1)
```

Please change the define in serial_log.h to something else, e.g. `__FILE_NAME__`

**Comment by cotestatnt** [comment]
Thanks @DeWonderMan 
I've done as you suggested 👍
