### ISSUE TITLE
In connection with closed #28 issue

### ISSUE THREAD

**Issue by woodlist** [cotestatnt/AsyncTelegram2#30]
Finally I got a time for testing the sketch. It has been accommodated for GSM network usage. The Telegram connection test was passed successfully (local terminal report). The "welcome" interactive message reaches to the bot. But the actual update always falls, being treated as "File is unavailable. Maybe size limit 20MB was reached or file deleted", due to boolean "msg.document.file_exists" being false. In meantime the test print of the string "msg.document.file_path" variable on monitor return blank string.

[https://github.com/cotestatnt/AsyncTelegram2/issues/28](url)

**Comment by woodlist** [comment]
I have inquired also the "msg.document.file_name" It is also empty.

**Comment by cotestatnt** [comment]
Thanks @woodlist for your precious feedback.
I'm going to set-up a GSM test environment in order to check what's happening.

I will inform you about result of my tests.

**Comment by cotestatnt** [comment]
Hi @woodlist. I've hot a SIM card and a SIM800C module.

Could you share the test sketch you are trying up now?

**Comment by woodlist** [comment]
Dear @cotestatnt, please review the code.
`#include <time.h>
#include "HTTPUpdate.h"
#include <AsyncTelegram2.h>
#include <SSLClient.h> // See the source at https://github.com/OPEnSLab-OSU/SSLClient
#include "trust_anchors.h" // Certifiacte generation utility: https://openslab-osu.github.io/bearssl-certificate-utility/

const char* token =  "xxxxxxxx:xxxxxxxxxxx-xxxxxxxxxxxxxxxxxxx";
int64_t chat_id = xxxxxxxxx;

const char* firmware_version = __TIME__;
const char* fw_password = "update";

// Select your modem:
#define TINY_GSM_MODEM_SIM800
#define TINY_GSM_RX_BUFFER   1024
#define rand_pin             39

#define SerialMon Serial
#define SerialAT Serial2

// Set serial for AT commands
//#define DUMP_AT_COMMANDS
//#define TINY_GSM_DEBUG SerialMon

// TTGO T-Call pins
#define MODEM_RST            5
#define LED_BUILTIN 2


const char apn[] = "internet"; // 
const char gprsUser[] = "";
const char gprsPass[] = "";
const char GSM_PIN[]   = "1111";

#include <TinyGsmClient.h>
TinyGsm modem(SerialAT);                          // sets GSM modem to serial1
TinyGsmClient GSMclient(modem);                   // client for GSM
SSLClient sslClient(GSMclient, TAs, (size_t)TAs_NUM, rand_pin);
AsyncTelegram2 myBot(sslClient);



// https://www.geeksforgeeks.org/find-number-of-days-between-two-given-dates/
using namespace std;
unsigned long Seconds;
// A date has day 'd', month 'm' and year 'y'
struct Date {
  int d, m, y;
};

// To store number of days in
// all months from January to Dec.
const int monthDays[12]
  = { 31, 28, 31, 30, 31, 30,
      31, 31, 30, 31, 30, 31
    };
int year3 = 0;
int month3 = 0;
int day3 = 0;
int hour3 = 0;
int min3 = 0;
int sec3 = 0;
float timezone = 0;

void getconnectedtoGSM() {
  // Restart takes quite some time
  // To skip it, call init() instead of restart()
  SerialMon.println("Initializing modem...");

  modem.restart();
  // modem.init();
  String modemInfo = modem.getModemInfo();
  SerialMon.print("Modem Info: ");
  SerialMon.println(modemInfo);
  SerialMon.print(SerialAT.readString());
  // modem.sendAT("command")

  // Unlock your SIM card with a PIN if needed
  if ( modem.getSimStatus() != 3 ) {
    modem.simUnlock(GSM_PIN);
  }
  SerialMon.print("Connecting to APN: ");
  // wdt_reset();
  SerialMon.print(apn);
  if (!modem.gprsConnect(apn, gprsUser, gprsPass)) {
    SerialMon.println(" fail, Do restart");
    ESP.restart();
  }
  else {
    SerialMon.println(" OK");
  }
  bool res = modem.isGprsConnected();
  SerialMon.println("Waiting for network...");
  if (res && !modem.waitForNetwork(600000L)) {
    delay(10000);
    return;
  }
  if (res) {
    SerialMon.println("GPRS status: connected");
    String IP = modem.getLocalIP();
    SerialMon.println("Local IP:" + IP);
    SerialMon.println("Requesting current network time");
    if (modem.getNetworkTime(&year3, &month3, &day3, &hour3, &min3, &sec3, &timezone)) {
      SerialMon.println("Year: " + String(year3) + "\tMonth: " + String(month3) + "\tDay: " + String(day3));
      SerialMon.println("Hour: " + String(hour3) + "\tMinute: " + String(min3) + "\tSecond: " + String(sec3));
      SerialMon.println("Timezone: " + String(timezone));
      calctime();
    }
    else SerialMon.println("GPRS status: fail");
  }
}
int countLeapYears(Date d)
{
  int years = d.y;

  // Check if the current year needs to be
  // considered for the count of leap years
  // or not
  if (d.m <= 2)
    years--;

  // An year is a leap year if it
  // is a multiple of 4,
  // multiple of 400 and not a
  // multiple of 100.
  return years / 4
         - years / 100
         + years / 400;
}

// This function returns number of
// days between two given dates
int getDifference(Date dt1, Date dt2)
{
  // COUNT TOTAL NUMBER OF DAYS
  // BEFORE FIRST DATE 'dt1'

  // initialize count using years and day
  long int n1 = dt1.y * 365 + dt1.d;

  // Add days for months in given date
  for (int i = 0; i < dt1.m - 1; i++)
    n1 += monthDays[i];

  // Since every leap year is of 366 days,
  // Add a day for every leap year
  n1 += countLeapYears(dt1);

  // SIMILARLY, COUNT TOTAL NUMBER OF
  // DAYS BEFORE 'dt2'

  long int n2 = dt2.y * 365 + dt2.d;
  for (int i = 0; i < dt2.m - 1; i++)
    n2 += monthDays[i];
  n2 += countLeapYears(dt2);

  // return difference between two counts
  return (n2 - n1);
}

int calctime()
{
  Date dt1 = { 1, 1, 0 };
  Date dt2 = { day3, month3, year3 };
  Seconds = hour3 * 3600 + min3 * 60 + sec3;
  sslClient.setVerificationTime((uint32_t)getDifference(dt1, dt2), (uint32_t)Seconds);
  SerialMon.println( "Difference between two dates is " + String(getDifference(dt1, dt2)) + " days");
  return 0;
}

void setup() {
  modem.setBaud(9600);
  SerialMon.begin(115200);
  pinMode(MODEM_RST, OUTPUT);
  digitalWrite(MODEM_RST, HIGH);
  pinMode(LED_BUILTIN, OUTPUT);
  SerialAT.begin(9600);
  getconnectedtoGSM();
  delay(1000);

  // Set the Telegram bot properies
  myBot.setUpdateTime(1000);
  myBot.setTelegramToken(token);

  // Check if all things are ok
  SerialMon.print("\nTest Telegram connection... ");
  myBot.begin() ? Serial.println("OK") : Serial.println("NOK");
  char welcome_msg[128];
  snprintf(welcome_msg, 128, "BOT @%s online\n/help all commands avalaible.", myBot.getBotName());
  myBot.sendTo(chat_id, welcome_msg);

  // We have to handle reboot manually after sync with TG server
  httpUpdate.rebootOnUpdate(false);
}

void loop() {
  if (!modem.isGprsConnected()) {
    ESP.restart();
  }
  static uint32_t ledTime = millis();
  if (millis() - ledTime > 300) {
    ledTime = millis();
    digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN));
  }

  // a variable to store telegram message data
  TBMessage msg;

  // if there is an incoming message...
  if (myBot.getNewMessage(msg))
  {
    String tgReply;
    static String document, document1;
    switch (msg.messageType) {
      case MessageDocument :
        {
          document = msg.document.file_path;
          document1 = msg.document.file_name;
          SerialMon.println("msg.document.file_name: " + document1 + "  msg.document.file_path: " + document);
          if (msg.document.file_exists) {

            // Check file extension of received document (firmware must be .bin)
            if ( msg.document.file_path.endsWith(".bin")) {
              char report [128];
              snprintf(report, 128, "Start firmware update\nFile name: %s\nFile size: %d",
                       msg.document.file_name, msg.document.file_size);
              // Inform user and query for flash confirmation with password
              myBot.sendMessage(msg, report, "");
              msg.force_reply = true;
              myBot.sendMessage(msg, "Please insert password", "");
            }
          }
          else {
            myBot.sendMessage(msg, "File is unavailable. Maybe size limit 20MB was reached or file deleted");
          }
          break;
        }

      case MessageReply:
        {
          tgReply = msg.text;
          // User has confirmed flash start with right password
          if ( tgReply.equals(fw_password) ) {
            myBot.sendMessage(msg, "Start flashing... please wait (~30/60s)");
            handleUpdate(msg, document);
            document.clear();
          }
          // Wrong password
          else {
            myBot.sendMessage(msg, "You have entered wrong password");
          }
          break;
        }

      default:
        {
          tgReply = msg.text;
          if (tgReply.equalsIgnoreCase("/version")) {
            String fw = "Version: " + String(firmware_version);
            myBot.sendMessage(msg, fw);
          }
          else {
            myBot.sendMessage(msg, "Send firmware binary file ###.bin to start update\n"
                              "/version for print the current firmware version\n");
          }
          break;
        }
    }
  }

}



// Install firmware update
void handleUpdate(TBMessage &msg, String file_path) {

  String report;
  SerialMon.print("Firmware path: ");
  SerialMon.println(file_path);

  httpUpdate.onProgress([](int cur, int total) {
    static uint32_t sendT;
    if (millis() - sendT > 1000) {
      sendT = millis();
      SerialMon.printf("Updating %d of %d bytes...\n", cur, total);
    }
  });

  t_httpUpdate_return ret = httpUpdate.update(sslClient, file_path);
  SerialMon.println("Update done!");
  sslClient.stop();
  file_path.clear();

  switch (ret)
  {
    case HTTP_UPDATE_FAILED:
      report = "HTTP_UPDATE_FAILED Error (";
      report += httpUpdate.getLastError();
      report += "): ";
      report += httpUpdate.getLastErrorString();
      myBot.sendMessage(msg, report, "");
      break;

    case HTTP_UPDATE_NO_UPDATES:
      myBot.sendMessage(msg, "HTTP_UPDATE_NO_UPDATES");
      break;

    case HTTP_UPDATE_OK:
      myBot.begin();
      myBot.sendMessage(msg, "UPDATE OK.\nRestarting in few seconds...");

      // Wait until bot synced with telegram to prevent cyclic reboot
      while (!myBot.noNewMessage()) {
        Serial.print(".");
        delay(50);
      }
      ESP.restart();

      break;
    default:
      break;
  }

}`

**Comment by woodlist** [comment]
Hello @cotestatnt !
I did clean install of Win10 and newest Arduino IDE 1.8.19 Upon introduced above sketch compilation I got some warnings, connected with your library, namely:
`In file included from C:\Users\user\Documents\Arduino\libraries\AsyncTelegram2\src/AsyncTelegram2.h:40,
                 from C:\Users\user\Documents\Arduino\ESP\GPS-Vahe_CTBot_OTA\GPS-Vahe_CTBot_OTA.ino:3:
C:\Users\user\Documents\Arduino\libraries\AsyncTelegram2\src/serial_log.h:10: warning: "__FILENAME__" redefined
 #define __FILENAME__ (strrchr(__FILE__, '\\') ? strrchr(__FILE__, '\\') + 1 : __FILE__)
 
In file included from c:\users\user\documents\arduinodata\packages\esp32\tools\xtensa-esp32-elf-gcc\gcc8_4_0-esp-2021r2\xtensa-esp32-elf\sys-include\sys\reent.h:503,
                 from C:\Users\user\Documents\ArduinoData\packages\esp32\hardware\esp32\2.0.2/tools/sdk/esp32/include/newlib/platform_include/sys/reent.h:17,
                 from c:\users\user\documents\arduinodata\packages\esp32\tools\xtensa-esp32-elf-gcc\gcc8_4_0-esp-2021r2\xtensa-esp32-elf\sys-include\stdio.h:60,
                 from C:\Users\user\Documents\ArduinoData\packages\esp32\hardware\esp32\2.0.2\cores\esp32/Arduino.h:27,
                 from sketch\GPS-Vahe_CTBot_OTA.ino.cpp:1:
C:\Users\user\Documents\ArduinoData\packages\esp32\hardware\esp32\2.0.2/tools/sdk/esp32/include/newlib/platform_include/assert.h:38: note: this is the location of the previous definition
 #define __FILENAME__ (__builtin_strrchr( "/" __FILE__, '/') + 1)`
Seems the Arduino developer team have done a hard work over new release.
I got also "#define LED_BUILTIN 2" redefining warning and have fixed that by commenting out this definition.

**Comment by woodlist** [comment]
I would like to share an report. Upon recent lib update compilation above posted warnings gone. Unfortunately right now I'm unable to test the code on real hardware, thus I keep the status of this issue yet open.

**Comment by cotestatnt** [comment]
Thanks @woodlist.
Unfortunately I have not been able to set up a test project that uses a GSM modem because at the moment I don't have the necessary hardware.

Have you made any progress?

**Comment by woodlist** [comment]
Dear @cotestatnt, greetings.
I do report that the msg.document.file_path  is yet empty on terminal view. Accordingly, the OTA does not work.

**Comment by woodlist** [comment]
@cotestatnt Wow, I have fixed the problem. In AsyncTelegram2.cpp
`    doc.file_path = "https://api.telegram.org/file/bot" ;
    doc.file_path += m_token;
    doc.file_path += "/";`
were chaged to 
`    doc.file_path = F("https://api.telegram.org/file/bot") ;
    doc.file_path += m_token;
    doc.file_path += F("/");`
aaaand, it works now!

**Comment by woodlist** [comment]
[https://github.com/cotestatnt/AsyncTelegram2/tree/dev/test/ESP32_OTA_password](url)
@cotestatnt Please, revert back.

**Comment by cotestatnt** [comment]
Sorry @woodlist , I was tidying up the repos and forgot to restore the dev branch. Now it's online again.



> Wow, I have fixed the problem. In AsyncTelegram2.cpp...

This is a great news! 
It would be really really appreciated if you want share the code from your working example and create a pull request with your fix in AsyncTelegram2.cpp

Thanks!

**Comment by woodlist** [comment]
Dear @cotestatnt 
Having fixed things with AsyncTelegram2 however I was unhappy with overall performance, due to used SSL wrapper [https://github.com/OPEnSLab-OSU/SSLClient](url). Your simple non-blocking LED indicator is an very handy instrument on microcontroller's good standing visual checking. Thus it has been discovered that the MC getting stuck too much frequently, drops the network connection and restarts. Having done a hard work I find another library, available at [https://github.com/govorox/SSLClient](url) which works too much better then used library before. The only headache was the valid telegram certificate obtaining. I have tried to export the cert from MS Edge and Chrome browsers, but those were not the same in first, and the both did not worked in second. Then I have used ready made one at [https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/blob/master/src/TelegramCertificate.h](url) and now the performance is really good. As you are suggesting, I will prepare an sketch, which uses the GSM network connection, for your Examples.

**Comment by woodlist** [comment]
Having used the SSL wrapper from [https://github.com/govorox/SSLClient](url), seems the certificate, available at [https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/blob/master/src/TelegramCertificate.h](url) does not rely to [telegram.org](url), but to Go Daddy Root Certificate Authority. I cannot understand yet, how the certificate of root authority acts as valid one for Telegram. Meanwhile, this certificate is valid until 2037 year. Who can advice, am I wrong? Any attempt to download nor export the Telegram certificate from original server and further use in microcontroller code returned no connection with Telegram server.
