### ISSUE TITLE
Make a phone call via Telegram

### ISSUE THREAD

**Issue by joroMaser** [cotestatnt/AsyncTelegram2#45]
Can you add please that option?
Make a phone call via Telegram.

**Comment by cotestatnt** [comment]
Hi @joroMaser.

As I know, a bot can't do a phone call.
At most it could send a recorded audio message.

**Comment by joroMaser** [comment]
And how can I send recorded audio please?

**Comment by cotestatnt** [comment]
For the moment you can't. 
I have to add the method `sendDocument()` to the library...
It shouldn't take a lot of work because it's the same mechanism used to send images already up and running.
As soon as I have some free time, I'll add this feature!
