### ISSUE TITLE
How to disable the bot?

### ISSUE THREAD

**Issue by phazz1980** [cotestatnt/AsyncTelegram2#51]
When for some reason the connection to the bot router is lost when trying to connect, the ESP 32 cycle becomes 20 seconds. How can I turn it off when there is no connection?

P.S. I don’t know English well, translated through Google )

**Comment by phazz1980** [comment]
00:52:28.002 -> [D][AsyncTelegram2.cpp:28] checkConnection():	Start handshaking...
this freeze

**Comment by cotestatnt** [comment]
Hi @phazz1980 
I'm sorry for late reply, but i'm very busy in these days.

You could check the connection in the main loop() and avoid to call ` if (myBot.getNewMessage(msg)) {  ... ` which is then 
 responsible to call checkConnection() method.

**Comment by cotestatnt** [comment]
I'm going to close this issue for inactivity.
Reopen if you need more info.

**Comment by phazz1980** [comment]
This situation occurs when there is a wi-fi connection but no internet connection

**Comment by phazz1980** [comment]
if (initialized && WiFi.isConnected() &&myBot.getNewMessage(msg))
