### ISSUE TITLE
Alternative to telegram-bot

### ISSUE THREAD

**Issue by droidprova** [cotestatnt/AsyncTelegram2#55]
Hi Tolentino, considering the "hot" moment that the world is going through, do you think that telegram servers or itself could be banned by the international community?  Is there a valid and free alternative to telegram-bots that can be integrated into small iot projects? 
Hello and thank very much

**Comment by cotestatnt** [comment]
Hi @droidprova 
Telegram from what I understand is proving to be a good tool "against" war.
I have no idea how the situation will evolve. There are other similar services that make APIs available, such as Discord

**Comment by droidprova** [comment]
Thank you very much.

**Comment by cotestatnt** [comment]
You're welcome!
