### ISSUE TITLE
IL vecchio ESPTelegramBOT....

### ISSUE THREAD

**Issue by migreco2** [cotestatnt/AsyncTelegram2#6]
Ciao Tolentino
Usavo tantissimo il precedente ESPTelegramBOT che non so per quale ragione mi da sempre Message not delivered....mi viene il dubbio che ho aggiornato qualche libreria di IDE senza rendermi conto...
Lo hai eliminato? Forse perché usava ArduinoJson 5?
Mi sai aiutare?
Grazie
Mic

**Comment by cotestatnt** [comment]
Perdonami @migreco2, ma ESPTelegramBOT non è una mia libreria. Non saprei come aiutarti, mi spiace.

**Comment by migreco2** [comment]
Scusami…. La vedevo collegata a te e poi cancellata
Qui:

https://freesoft.dev/program/109600855

Comunque ho risolto … era la versione della ESP32 dev che deve essere 1.0.4 e la 1.0.6 non era più compatibile
Grazie comunque
