### ISSUE TITLE
Could not compile EventScheduler.ino

### ISSUE THREAD

**Issue by Dcmwrnd** [cotestatnt/AsyncTelegram2#60]
Hello Owner,

Your AsyncTelegram2 is fantastic. Great job.

Recently I tried to compile your Examples/AsyncTelegram2/advanced/EventScheduler.ino on:-
Arduino IDE v1.8.19
ArduinoJson v6.19.2
ESP32 Board Manager v1.0.6

and giving me error below here.

exit status 1
cannot convert 'String' to 'const char*' for argument '1' to 'int strcmp(const char*, const char*)'

Error at line: 148 of (ev_scheduler.h).

**Comment by cotestatnt** [comment]
Hi @Dcmwrnd 
Thanks for your support.

This error is due to one the latest release where I've changed the type of some variables.

Change this kind of lines along the sketch
```
 else if (!strcmp (theMsg.callbackQueryData, WEEKEND)) {
```

in this way:
```
 else if (theMsg.callbackQueryData.equals(WEEKEND)) {
```

As soon as I can, I will update also the example online.

**Comment by joroMaser** [comment]
@cotestatnt maybe it good idea to add the compilation of all example in Action . So it will test each commit.
