### ISSUE TITLE
Very serious BUG 

### ISSUE THREAD

**Issue by zkasa** [cotestatnt/AsyncTelegram2#65]
Wherever DynamicJsonDocument is used, there is this bug! A local instance of this object is created inside the method. Pointers to strings (char*) from the fields of this object are assigned to the fields of the 'message' variable and the method returns control to the outside. However, the local instance of the 'updateDoc' is destroyed when exiting the method and ALL pointers to strings become invalid!

**Comment by cotestatnt** [comment]
Hi @zkasa 
Yes you are right and this bug was already reported.

For this reason the use of `char *` and `const char *` for strings has been abandoned in favor of String variables which will be available starting from next release
