### ISSUE TITLE
Verify message delivery

### ISSUE THREAD

**Issue by aXx12** [cotestatnt/AsyncTelegram2#71]
Is there a way in the library to make sure the message is sent and delivered to the recipient? For example, if due to problems with the Internet connection or the telegram server, the message was sent (or not sent), but not delivered to the recipient, is it possible to find out about this and send it again?

**Comment by cotestatnt** [comment]
From bot side, you have no way to know if Telegram has delivered message to user (I assume that server has its own internal verification mechanisms), but for sure you can check if message from bot was delivered to Telegram server.
Check [this example](https://github.com/cotestatnt/AsyncTelegram2/blob/master/examples/sendMessageCallback/sendMessageCallback.ino) for how-to.
