### ISSUE TITLE
suggest a possible solution to the problem

### ISSUE THREAD

**Issue by Demon-MC** [cotestatnt/AsyncTelegram2#79]
last night one of the members of the group where the bot is installed threw a very large text into the chat
![9627DC1A-5CA5-45E8-B0A4-6CFC09F3CA76](https://user-images.githubusercontent.com/610046/168392654-44bd410b-c886-40d9-b55b-3ba4730201aa.jpeg)
after that esp8266 hung.  there is no way to check the console.  esp8266 also stopped sending information from sensors to the Internet.
![90F20BDF-7667-4E24-976D-E87F25D69405](https://user-images.githubusercontent.com/610046/168393036-61839705-bc4d-4b2a-9cba-0967353cf61f.jpeg)
passed the last information from the esp sensors before sending a large text to the chat

question: how to protect esp from large text messages in chat so that the bot skips them and does not process them?  especially messages in Cyrillic.

**Comment by Demon-MC** [comment]
forgot to write.  esp continues to work and pings over the network.  but the loop function hung at some point

**Comment by joroMaser** [comment]
https://github.com/cotestatnt/AsyncTelegram2/blob/master/src/AsyncTelegram2.cpp#L218-L231
Is that section didn't run? @Demon-MC

**Comment by Demon-MC** [comment]
I'm not sure about this yet.. is there any way in c++ code to set the maximum length of the received command message
