### ISSUE TITLE
Stack canary watchpoint triggered

### ISSUE THREAD

**Issue by eloquentarduino** [cotestatnt/AsyncTelegram2#92]
I'm using your library to send Esp32-cam pictures to Telegram. The first one gets delivered, the second goes in error somewhere but I still cannot detect where, the third makes the board reboot with a "Stack canary watchpoint triggered" exception.

Any guess?

Project here --> https://github.com/eloquentarduino/EloquentEsp32cam/blob/main/examples/16_Telegram_Notifications/16_Telegram_Notifications.ino

**Comment by cotestatnt** [comment]
Hi @eloquentarduino, I'm sorry for the big late reply, but I've been very busy in recent months.

Do you still have this problem or did you manage to solve it?
I ran into the same problem with the example included in the library a while ago, but I should have fixed it.
